### Creates a new Patient entity
POST http://localhost:4000/patients
Content-Type:  application/json

{
  "name": "Jhon Doe with a billing account",
  "email": "test_billing_account1@example.com",
  "address": "123 main street22",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2024-11-28"

}
###