### Creates a new Patient entity
POST http://localhost:4000/patients
Content-Type:  application/json

{
  "name": "Jhon Doe Kafka Test",
  "email": "kafka_test@example.com",
  "address": "123 main street22",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2024-11-28"

}
###