name: Patient Service CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build patient-service
        run: mvn -B clean package --file patient-service/pom.xml -DSkipTests

      - name: Build billing-service
        run: mvn -B clean package --file billing-service/pom.xml -DSkipTests

      - name: Build analytics-service
        run: mvn -B clean package --file analytics-service/pom.xml -DSkipTests

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}

      - name : Build & push patient-service
        run: |
          IMAGE_NAME=ghcr.io/${{github.repository_owner}}/patient-service:latest
          docker build -t $IMAGE_NAME patient-service/
          docker push $IMAGE_NAME


      - name: Build & push billing-service
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/billing-service:latest
          docker build -t $IMAGE_NAME billing-service/
          docker push $IMAGE_NAME
      

      - name: Build & push analytics-service
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/analytics-service:latest
          docker build -t $IMAGE_NAME analytics-service/
          docker push $IMAGE_NAME